#############################################################################
# Makefile for building: socketio
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  socketio.pro
# Template: subdirs
# Command: C:\Qt\Qt5.4-new\5.4\mingw491_32\bin\qmake.exe -spec win32-g++ -o Makefile socketio.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\Qt5.4-new\5.4\mingw491_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src \
		sub-examples


sub-src-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile
	cd src\ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-examples-qmake_all: sub-src-qmake_all FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && $(QMAKE) E:\DDuiZhijiao\QtSocketIo\examples\examples.pro -spec win32-g++ -o Makefile
	cd examples\ && $(MAKE) -f Makefile qmake_all
sub-examples: sub-src FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\examples\examples.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile
sub-examples-make_first: sub-src-make_first FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\examples\examples.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-examples-all: sub-src-all FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\examples\examples.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-examples-clean: sub-src-clean FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\examples\examples.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-examples-distclean: sub-src-distclean FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\examples\examples.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-examples-install_subtargets: sub-src-install_subtargets FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\examples\examples.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-examples-uninstall_subtargets: sub-src-uninstall_subtargets FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\examples\examples.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: socketio.pro .qmake.conf .qmake.cache C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/win32-g++/qmake.conf C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/spec_pre.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/qdevice.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/device_config.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/common/shell-win32.conf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/qconfig.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_declarative.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_declarative_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_enginio.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_enginio_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_script.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_script_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_scripttools.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_webkit.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_webkit_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_webview.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_webview_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		mkspecs/modules-inst/qt_lib_socketio.pri \
		mkspecs/modules-inst/qt_lib_socketio_private.pri \
		mkspecs/modules/qt_lib_socketio.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/qt_functions.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/qt_config.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/win32/qt_config.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/win32-g++/qmake.conf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/spec_post.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/qmodule.pri \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/qt_build_config.prf \
		.qmake.conf \
		.qmake.cache \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/exclusive_builds.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/default_pre.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/win32/default_pre.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/configure.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/qt_parts.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/resolve_config.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/default_post.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/qt_example_installs.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/exceptions_off.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/qt_docs_targets.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/win32/rtti.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/precompile_header.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/warn_on.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/win32/windows.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/testcase_targets.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/yacc.prf \
		C:/Qt/Qt5.4-new/5.4/mingw491_32/mkspecs/features/lex.prf \
		socketio.pro
	$(QMAKE) -spec win32-g++ -o Makefile socketio.pro
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\spec_pre.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\qdevice.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\device_config.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\common\shell-win32.conf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\qconfig.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_core.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_declarative.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_declarative_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_enginio.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_enginio_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_help.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_location.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_network.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_script.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_webkit.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_webkit_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
mkspecs\modules-inst\qt_lib_socketio.pri:
mkspecs\modules-inst\qt_lib_socketio_private.pri:
mkspecs\modules\qt_lib_socketio.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\qt_functions.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\qt_config.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\win32\qt_config.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\win32-g++\qmake.conf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\spec_post.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\qmodule.pri:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\qt_build_config.prf:
.qmake.conf:
.qmake.cache:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\exclusive_builds.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\default_pre.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\win32\default_pre.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\configure.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\qt_parts.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\resolve_config.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\default_post.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\qt_example_installs.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\exceptions_off.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\qt_docs_targets.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\win32\rtti.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\precompile_header.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\warn_on.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\win32\windows.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\testcase_targets.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\yacc.prf:
C:\Qt\Qt5.4-new\5.4\mingw491_32\mkspecs\features\lex.prf:
socketio.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ -o Makefile socketio.pro

qmake_all: sub-src-qmake_all sub-examples-qmake_all FORCE

make_first: sub-src-make_first FORCE
all: sub-src-all sub-examples-all FORCE
clean: sub-src-clean sub-examples-clean FORCE
distclean: sub-src-distclean sub-examples-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

sub-src-debug:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-src-debug

sub-src-release:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile release
release: sub-src-release

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

sub-src-install_html_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install_html_docs
install_html_docs: sub-src-install_html_docs

sub-src-uninstall_html_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall_html_docs
uninstall_html_docs: sub-src-uninstall_html_docs

sub-src-install_qch_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install_qch_docs
install_qch_docs: sub-src-install_qch_docs

sub-src-uninstall_qch_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall_qch_docs
uninstall_qch_docs: sub-src-uninstall_qch_docs

sub-src-install_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install_docs
install_docs: sub-src-install_docs

sub-src-uninstall_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall_docs
uninstall_docs: sub-src-uninstall_docs

sub-src-qch_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile qch_docs
qch_docs: sub-src-qch_docs

sub-src-prepare_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile prepare_docs
prepare_docs: sub-src-prepare_docs

sub-src-generate_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile generate_docs
generate_docs: sub-src-generate_docs

sub-src-check:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\DDuiZhijiao\QtSocketIo\src\src.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

