QT.socketio_private.VERSION = 5.4.0
QT.socketio_private.MAJOR_VERSION = 5
QT.socketio_private.MINOR_VERSION = 4
QT.socketio_private.PATCH_VERSION = 0
QT.socketio_private.name = QtSocketIo
QT.socketio_private.libs = $$QT_MODULE_LIB_BASE
QT.socketio_private.includes = $$QT_MODULE_INCLUDE_BASE/QtSocketIo/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtSocketIo/5.4.0/QtSocketIo
QT.socketio_private.depends = socketio
QT.socketio_private.module_config = internal_module no_link
